# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

variables:
  TAG: data-platform

stages:
  - install
  - build-test
  - build-pro
  - build-pre
  - build-prod

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

install-deps:
  stage: install
  tags:
    - dp-app
  only:
    - test
    - pro
    - pre
    - prod
  script:
    - yarn install

# build-test:
#   stage: build-test
#   tags:
#     - dp-server
#   only:
#     - test

build-pro:
  stage: build-pro
  only:
    - pro
  tags:
    - dp-app
  script:
    - VERSION=$(node -p -e "require('./package.json').version")
    - DATE=$(date +%F_%H%M)
    - tar czvf pack-tmp.tar.gz  --exclude=.git --exclude=chromium --exclude=pack-tmp.tar.gz ./
    - scp pack-tmp.tar.gz front@52.83.142.85:/data/www/downloads/${TAG}/${TAG}-server-pro-${VERSION}.${DATE}.tar.gz
    - rm -f pack-tmp.tar.gz
